### ISSUE TITLE
Original code loads the file from "destination" and writes to "newDestination" 

### ISSUE THREAD

**Issue by etni** [ivaylokenov/MyTested.AspNet.TV#1]
original code: 
https://github.com/ivaylokenov/MyTested.AspNet.TV/blob/f339c5a3896c88c582cac389c1f016528fa38e80/src/The%20Rules%20for%20TESTABLE%20C%23%20Code%20Design/Before/Blog.Services/ImageService.cs#L23-L37

new code: 
https://github.com/ivaylokenov/MyTested.AspNet.TV/blob/f339c5a3896c88c582cac389c1f016528fa38e80/src/The%20Rules%20for%20TESTABLE%20C%23%20Code%20Design/After/Blog.Services/Images/ImageProcessorService.cs#L22-L31

I think the resize method should have a Source and Destination parameters.

**Comment by ivaylokenov** [comment]
You are correct. I introduced a bug during the refactoring. Nice catch, thank you for reporting. Not sure whether I should fix it in the repository or leave it to be like in the video.

**Comment by etni** [comment]
ok, great.  Thanks for the great content on the videos.
